### ISSUE TITLE
Null response when deleting a campaign

### ISSUE THREAD

**Issue by timsim00** [salesforce-marketingcloud/FuelSDK-Node-REST#57]
It deletes the campaign but .then(response) returning null.

**Comment by vernak2539** [comment]
@timsim00 if you could give more detail that would be great. Things I need would be:

1. Example setup (minus keys/secrets)
1. The response from the API

**Comment by timsim00** [comment]
Not much to it.  The row is deleted but the response is null.

		var options = {
			uri: this.endpoint + '/' + this.config.id
		};

		this.parent.RestClient
			.delete(options)
			.then(function(response) {
				console.log('then',response);  <---- Null here.
				cb(response); 
			}.bind(this))
			.catch(function(err) {
				cb(err); 
			}.bind(this));
	}

**Comment by vernak2539** [comment]
@timsim00 Can you please provide the reply from the API (status, msg, etc)?

**Comment by timsim00** [comment]
I added console.logs to fuel-rest.js starting at line 101:

				request(options, function(err, res, body) {
					var parsedBody, restResponse;
					console.log('body',body);
					console.log('err',err);
					console.log('res',res);


Here's the console:

body 
err null
res {the entire response object with only meaningful data:
  statusCode: 200,
  statusMessage: 'OK',
 body: ''
}
then null
campaign.delete null

**Comment by vernak2539** [comment]
Okay, I will update something to deliver the status code and message if no body exists. Would assume this is the same for post (sometimes), put, and patch in addition to delete
