### ISSUE TITLE
ReDOS Vulnerability: request npm module dependency

### ISSUE THREAD

**Issue by benjaminpearson** [salesforce-marketingcloud/FuelSDK-Node-REST#73]
Prior to version 2.47.0 the `request` npm module was using `tough-cookie` < 2.3.0 which has a high ReDOS vulnerability rating. They have updated to use the newest version of `tough-cookie` that does not have the vulnerability in >= 2.47.0 version of `request`.

**Read more:**
https://nodesecurity.io/advisories/130
https://snyk.io/vuln/npm:tough-cookie:20160722

**Comment by vernak2539** [comment]
the version of `request` used in this module is ~2.72.0

**Comment by benjaminpearson** [comment]
Sorry @vernak2539 I unfortunately incorrectly typo'd twice. I meant to write version `2.74.0`.

**Comment by vernak2539** [comment]
@benjaminpearson updated. Thanks!
