### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by uxsoft** [salesforce-marketingcloud/FuelSDK-Node-REST#75]
Would it be possible to add an option to configure proxy settings?

We're using a modified version of this library like this and would like to switch to a non modified npm version for obvious reasons.
 
```javascript
Line 100
options.uri     = helpers.resolveUri(self.origin, options.uri);
				options.headers = _.merge({}, self.defaultHeaders, options.headers);
				options.headers.Authorization = options.headers.Authorization || 'Bearer ' + authResponse.accessToken;
				if(proxy.useProxy()) {
					options.proxy = proxy.getUri();
				}
				options.rejectUnauthorized = merck.security.rejectUnauthorized;
```

**Comment by vernak2539** [comment]
@uxsoft sounds like a great idea. Could you submit a PR?

**Comment by vernak2539** [comment]
Actually, I believe this can be accomplished already. 

When you make your request (get|post|etc), you can pass those options as the first parameter. The `options` parameter will be passed directly to the request module. You should be able to specify the proxy settings there.

Something like below would work I think. It looks like you may have an old version of the module. May want to update it as below is based off the most recent version.

```js
client.get({
  uri: 'whatever/uri/you/want',
  proxy: proxy.getUri(),
  rejectUnauthorized: merck.security.rejectUnauthorized,
  // everything else
}, function(err, response) {
   // do whatever
});
```

**Comment by uxsoft** [comment]
I just inherited this code and was told to fix it. I have no idea how much of the code is from the SDK and how much is our work, however the folder also contains a file called ET_Client and a folder called objects with javascript classes regarding the actual api methods. I couldn't find these anywhere in any of the npm packages even though the code looks like to be from the original js sdk?.

We're using this to  send an email using the triggeredsend method. 

Is this way of using the sdk deprecated, or is a new package with this stuff available somewhere?

**Comment by vernak2539** [comment]
@uxsoft okay. First off, not sure what the version of the client you're using is. If you could look in the `package.json`, we can find out.

Using your example of code above, I think below would probably work for you. Again, I've done this with the latest version of the module.


```js
// options === whatever you pass in during initialisation
var client = new FuelRest(options);

var requestOptions = {
  uri: '/whatever/api/you/are/accessing',
  rejectUnauthorized: merck.security.rejectUnauthorized
};

if(proxy.useProxy()) {
  requestOptions.proxy = proxy.getUri();
}

// "get" could be subsituted for any of the HTTP methods or apiRequest
client.get(requestOptions, function(err, response) {
  // it only errors here if the request module errors, not if the API returns an invalid response
});
```

In regards to 

> ET_Client and a folder called objects with javascript classes regarding the actual api methods

I believe this is what you're looking for. It hasn't been maintained for a while

https://github.com/salesforce-marketingcloud/FuelSDK-Node

**Comment by uxsoft** [comment]
Yes, that is exactly what I was looking for. Does it mean that it doesn't work with the current version with the fuel-rest and fuel-soap libraries? So is the recommended way now just using these directly? 

Because setting the proxy is a problem there and if its deprecated, I'll just use only fuel-rest to craft the request manually and call it a day. Otherwise I'll move this issue to that repo and possibly submit a PR there with a fix.

Anyway thanks a lot for help!

**Comment by vernak2539** [comment]
@uxsoft no worries. It seems that they are updating that module every so often now. It looks as if it has the newest REST module as a dependency, I'm just not sure how they pass options down to the actual requests.

Good luck.

_Sometimes I do work on that one, so if they're not responsive or you need a PR merged, please let me know_
