### ISSUE TITLE
Retry doesn't help

### ISSUE THREAD

**Issue by jaypeng2015** [salesforce-marketingcloud/FuelSDK-Node-REST#76]
Version: 2.0.5

On get | post | put | patch | delete requests, the `retry` options is true by default.
Ideally this will re-fetch the access token and make the request again after receiving a 401 error.

However, by the following logic in `_processRequest` function, the `Authorization` header will only be updated when it doesn't exist, which means the second request will still take the old token and then always get a 401 error again.

```
if (!options.headers.Authorization) {
	options.headers.Authorization = 'Bearer ' + authResponse.accessToken;
	retry = options.retry || false;
}
```

**Comment by vernak2539** [comment]
@nathan-boyd do you remember why we did this?

**Comment by jaypeng2015** [comment]
It's been almost year now and I still have to use `invalidateToken` and resend the request again on 401, with the latest sdk version...  :(

**Comment by vernak2539** [comment]
@jaypeng2015 I'm sorry about that. Since I did not get any response about this, would you mind submitting a PR with the requested changes? I can then get a new version out for you

**Comment by jaypeng2015** [comment]
@vernak2539 I have created a PR however the CI fails because the project doesn't support Node 10.

**Comment by vernak2539** [comment]
I will take a look at it and try to get it working
