### ISSUE TITLE
More examples in readme

### ISSUE THREAD

**Issue by HauntedSmores** [salesforce-marketingcloud/FuelSDK-Node-REST#85]
It would be really helpful to have a more comprehensive set of examples, especially while there are discrepancies between the SOAP and REST APIs. Specifically a post request.

**Comment by vernak2539** [comment]
You can have a look at [this page](https://developer.salesforce.com/docs/atlas.en-us.noversion.mc-apis.meta/mc-apis/routes.htm) for all the available routes. These can then be combined to to do different things. 

Feel free to submit a PR with more comprehensive examples if you'd like. We're always looking for help!
